# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            form_login:
                login_path: demos_task_admin
                check_path: demos_task_admin_check
            logout:
                path: /task/logout
                target: /task

        default:
            anonymous: ~
